/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ScientificCalculator calc = new ScientificCalculator();
        // double result= calc.cubeOf(4.0);
        // System.out.println("cube =" + result);

        int result= calc.modulo(5, 2);
        //double result= calc.modulo_double(5.0, 2.0);

        System.out.println("modulo =" + result);
        //System.out.println("modulo =" + result3);


        // System.out.println(new App().getGreeting());
        // StandardCalculator calc = new StandardCalculator();
        // calc.add(1, 1);
        // System.out.println(calc.getResult());
        // calc.clearResult();
        // System.out.println(calc.getResult());

        // calc.subtract(4, 5);
        // System.out.println(calc.getResult());
        // calc.multiply(7, 9);
        // System.out.println(calc.getResult());
        // calc.divide(9, 3);
        // System.out.println(calc.getResult());

    }
}

